POST http://localhost:3001/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImRlZXBmYXRob20yQGdtYWlsLmNvbSIsImlhdCI6MTczNDUwNTkxMiwiZXhwIjoxNzM0NTA5NTEyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.2Vq-jYTT6MA8eOQHo31EoQI3NMeZZ1vJ8LsBCPevT9U

{
  "title": "What is Disparaue2?",
  "postType": "post",
  "slug": "post-2011",
  "status": "draft",
  "content": "test content",
  "schema": "{\"name\":\"John Doe\",\"age\":30,\"isStudent\":false,\"courses\":[\"Mathematics\",\"Physics\",\"Computer Science\"],\"address\":{\"street\":\"123 Main St\",\"city\":\"Anytown\",\"postalCode\":\"12345\"}}",
  "featuredImageUrl": "https://en.wikipedia.org/wiki/Sherlock_Holmes",
  "publishOn": "2024-03-16T07:46:32+0000",
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true, \"notifications\": false}"
  },
  "authorId": 1,
  "tags": [
    6,
    10,
    15
  ]
}