POST http://localhost:3001/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImRlZXBmYXRob20yQGdtYWlsLmNvbSIsImlhdCI6MTczNDUwODgwMSwiZXhwIjoxNzM0NTEyNDAxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.aFk-LMH28n4yQpQBulRCu5yoYayhCRfdICW1CcEgjuw

{
  "title": "What is Disparaue2s?",
  "postType": "post",
  "slug": "post-2011ss",
  "status": "draft",
  "content": "test content",
  "schema": "{\"name\":\"John Doe\",\"age\":30,\"isStudent\":false,\"courses\":[\"Mathematics\",\"Physics\",\"Computer Science\"],\"address\":{\"street\":\"123 Main St\",\"city\":\"Anytown\",\"postalCode\":\"12345\"}}",
  "featuredImageUrl": "https://en.wikipedia.org/wiki/Sherlock_Holmes",
  "publishOn": "2024-03-16T07:46:32+0000",
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true, \"notifications\": false}"
  },
  "tags": [
    2,
    5,
    6
  ]
}