PATCH http://localhost:3001/posts
Content-Type: application/json

{
  "id": 32,
  "title": "How NextJS differs from React?",
  "content": "Main differences of NextJS from React are ...",
  "postType": "post",
  "tags": [
    2,
    4
  ]
}