POST http://localhost:3001/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImRlZXBmYXRob20yQGdtYWlsLmNvbSIsImlhdCI6MTczNDQyMTE2NiwiZXhwIjoxNzM0NDI0NzY2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.MagJ1SiisV4cu-egx6zqg5dzJRBDuST1dswVa0EsBUM

{
  "firstName": "Deep",
  "lastName": "Fathom",
  "email": "deepfathodm2@gmail.com",
  "password": "Pa$$word1"
}

###

POST http://localhost:3001/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImRlZXBmYXRob20yQGdtYWlsLmNvbSIsImlhdCI6MTczNDQyMTE2NiwiZXhwIjoxNzM0NDI0NzY2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.MagJ1SiisV4cu-egx6zqg5dzJRBDuST1dswVa0EsBUM

{
  "users": [
    {
      "firstName": "Sherlock",
      "lastName": "Holmes",
      "email": "sherlockholmdes@gmail.com",
      "password": "Password123#"
    },
    {
      "firstName": "Hercule",
      "lastName": "Poirot",
      "email": "hercudle@gmail.com",
      "password": "Pa$$word1"
    },
    {
      "firstName": "John",
      "lastName": "Watson",
      "email": "jodhn@gmail.com",
      "password": "Pa$$word1"
    }
  ]
}

