POST http://localhost:3001/users
Content-Type: application/json

{
  "firstName": "Deep",
  "lastName": "Fathom",
  "email": "deepfathom@gmail.com",
  "password": "Pa$$word1"
}

###

POST http://localhost:3001/users/create-many
Content-Type: application/json

{
  "users": [
    {
      "firstName": "Sherlock",
      "lastName": "Holmes",
      "email": "sherlockholmes@gmail.com",
      "password": "Password123#"
    },
    {
      "firstName": "Hercule",
      "lastName": "Poirot",
      "email": "hercule@gmail.com",
      "password": "Pa$$word1"
    },
    {
      "firstName": "John",
      "lastName": "Watson",
      "email": "john@gmail.com",
      "password": "Pa$$word1"
    }
  ]
}

